FROM node:21

ARG PORT

# Add a work directory
WORKDIR /app
# Cache and Install dependencies
COPY package*.json ./
# RUN npm cache clean --force
# RUN npm cache verify
# RUN npm install
RUN npm i 
# RUN npm install --verbose
# Copy app files
COPY . .
# Build the app
# RUN npm run build
# Expose port
EXPOSE ${PORT}

# compile TS
# RUN npx tsc

RUN chmod +x wait-for-it.sh