FROM node:21

ARG PORT
ARG BACKEND_HOST
ARG BACKEND_PORT

ENV BACKEND_HOST=$BACKEND_HOST
ENV BACKEND_PORT=$BACKEND_PORT

# Add a work directory
WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm cache clean --force
RUN npm cache verify
RUN npm install --verbose

# Copy app files
COPY . .

# Build the app
RUN npm run build

# Expose port
EXPOSE ${PORT}

# Start the app
CMD [ "npm", "run", "start" ]